name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * *"

jobs:
  hacs:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: HACS Action
        uses: hacs/action@main
        with:
          category: plugin
